#!/bin/bash
pwd
0-current_working_directory
ls -a
chmod u+x 0-current_working_directory
git config user.email 'temidayoakanmu69@gmail.com'
git config user.name 'tmd4tech'
git add .
git commit -m 'working directory'
git push
